language: node_js
node_js:
  - "14"

cache:
  directories:
    - node_modules

branches:
  except:
  - e2e-test

jobs:
  include:
    # - stage: Lint, Test, Build
    #   name: Lint
    #   script:
    #     - npm install
    #     - npm run lint
    - stage: Lint, Test, Build
      name: Lint
      script:
        - npm install
        - npm run lint
    - name: Test
      script:
        - npm install
        - npm test
    - name: Build
      script:
        - npm install
        - cd app/client
        - npm install
        - npm run build
# {
#   "language": "node_js",
#   "os": [
#     "linux"
#   ],
#   "dist": "xenial",
#   "node_js": [
#     "14"
#   ],
#   "script": [
#     "cd app/server"
#     "npm install",
#     "npm test"
#   ]
# }